# Generated by Django 3.1.1 on 2020-09-14 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
