# Generated by Django 3.1.1 on 2020-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0002_remove_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Power System'), (1, 'Water System'), (2, 'Blade Server')], default=0),
        ),
    ]
