# Generated by Django 3.1.1 on 2020-09-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0003_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
