# Generated by Django 3.1.1 on 2020-09-18 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0006_auto_20200918_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
