# Generated by Django 3.1.1 on 2020-09-18 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0007_auto_20200918_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reserved_start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
