# Generated by Django 3.1.1 on 2020-09-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0011_auto_20200924_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reserved_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
