# Generated by Django 3.1.1 on 2020-10-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0012_reservation_reserved_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Power System'), (1, 'Water System'), (2, 'Blade Server')]),
        ),
    ]
