# Generated by Django 3.1.1 on 2020-10-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0015_auto_20201008_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('Power_System', 'Power System'), ('Water_System', 'Water System'), ('Blade', 'Blade Server')], max_length=30, null=True),
        ),
    ]
