# Generated by Django 3.1.1 on 2020-10-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0017_auto_20201009_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Power System'), (1, 'Water System'), (2, 'Blade Server')]),
        ),
    ]
