# Generated by Django 3.1.1 on 2020-10-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0018_auto_20201009_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(max_length=1, verbose_name='Power System = 0, Water System = 1, Blade Server = 2'),
        ),
    ]
