# Generated by Django 3.1.1 on 2020-10-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0020_auto_20201009_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='updated_datetime',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, max_length=30, verbose_name='Power System = 0, Water System = 1, Blade Server = 2'),
        ),
    ]
