# Generated by Django 3.0.3 on 2020-12-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0023_auto_20201130_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Power System'), (1, 'Water System')], default=0, verbose_name='Seçenekler'),
        ),
    ]
