# Generated by Django 3.0.3 on 2020-12-06 13:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0024_auto_20201203_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESXi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field', multiselectfield.db.fields.MultiSelectField(choices=[(0, 'ESXi1'), (1, 'ESXi2'), (2, 'ESXi3'), (3, 'ESXi4'), (4, 'ESXi5'), (5, 'ESXi6'), (6, 'ESXi7'), (7, 'ESXi8'), (8, 'ESXi9'), (9, 'ESXi10'), (10, 'ESXi20'), (11, 'ESXi21'), (12, 'ESXi22'), (13, 'ESXi23'), (14, 'ESXi24'), (15, 'ESXi25'), (16, 'ESXi26'), (17, 'ESXi27'), (18, 'ESXi28'), (19, 'ESXi29'), (20, 'ESXi30')], max_length=52)),
            ],
        ),
    ]
