# Generated by Django 3.0.3 on 2020-12-06 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0025_esxi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ESXi',
        ),
    ]
