# Generated by Django 3.0.3 on 2020-12-06 15:08

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rezervasyon', '0026_delete_esxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status3',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(5, 'ESXi5')], max_length=1, null=True, verbose_name='ESXi'),
        ),
    ]
